# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
                ('teacher_desc', models.TextField(verbose_name='教师简介')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 't_teacher',
            },
        ),
    ]
