# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 13:46
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 't_category',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='课程名')),
                ('teacher', models.CharField(max_length=20, verbose_name='主讲老师')),
                ('coure_sum', models.TextField(max_length=300, verbose_name='课程简介')),
                ('info', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='课程信息')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='course', verbose_name='封面')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 't_course',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='video.Tag', verbose_name='标签'),
        ),
    ]
